apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pusher-hpa
  namespace: betteruptime
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pusher
  minReplicas: 1          # Minimum pods to keep running
  maxReplicas: 2          # Maximum pods allowed
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75  # Scale up if CPU > 75%
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80  # Scale up if memory > 80%
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Percent
          value: 50       # Can increase up to 50% pods at a time
          periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 25       # Can decrease up to 25% pods at a time
          periodSeconds: 60
